all:
  children:
    managers:
      hosts:
        manager-1:
          ansible_host: 10.0.0.10
    workers:
      hosts:
        worker-1:
          ansible_host: 10.0.0.11
        worker-2:
          ansible_host: 10.0.0.12
        worker-3:
          ansible_host: 10.0.0.13
